name: Build Docker Image on Star

on:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/daviszerro/alpine-x-ui:latest
            ghcr.io/daviszerro/alpine-x-ui:${{ env.DATE }}
          
      - name: Pull and save Docker image
        run: |
          docker pull ghcr.io/daviszerro/alpine-x-ui:${{ env.DATE }}
          docker save ghcr.io/daviszerro/alpine-x-ui:${{ env.DATE }} > alpine-x-ui-${{ env.DATE }}.tar

      - name: Create Release and Upload Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.DATE }}
          name: Release ${{ env.DATE }}
          draft: false
          prerelease: false
          files: |
            alpine-x-ui-${{ env.DATE }}.tar
